@startuml

autonumber

SocketReader -> Quiche: drainCipherText(buffer)
SocketReader -> Quiche: feedCipherText(buffer)

Application -> Quiche: readableStreamIds()
Application -> Quiche: writableStreamIds()
Application -> Quiche: drainClearTextForStream(id, buffer) // TODO check that this is the moment Quiche enlarges the flow control window
Application -> Quiche: feedClearTextForStream(id, buffer) // TODO check that this is the moment Quiche shrinks the flow control window

@enduml