@startuml

autonumber

ConnectionManager -> ConnectionManager: select()
ConnectionManager -> ConnectionManager: processReadableKey()
ConnectionManager -> DatagramSocket: receive(buffer)
ConnectionManager -> Quiche: feedCipherText(buffer)
ConnectionManager -> Quiche: processStreams()
Quiche -> Quiche: readableStreamIds()
Quiche -> Quiche: writableStreamIds()
Quiche -> QuicStreamEndPoint: ewykExecute( () -> onSelected(readable, writable) )
QuicStreamEndPoint -> Application: fillable()

Application -> QuicStreamEndPoint: fill()
QuicStreamEndPoint -> Quiche: drainClearTextForStream() // drain quiche for cleartext
QuicStreamEndPoint -> Quiche: drainCipherText(buffer) // drain quiche for ciphertext (ACKs)
QuicStreamEndPoint -> DatagramSocket: send(buffer)

Application -> QuicStreamEndPoint: flush()
QuicStreamEndPoint -> Quiche: feedClearTextForStream() // feed quiche with cleartext
QuicStreamEndPoint -> Quiche: drainCipherText(buffer) // drain quiche for ciphertext
QuicStreamEndPoint -> DatagramSocket: send(buffer)

@enduml